# Generated by Django 5.0.6 on 2024-06-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo_eletrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(max_length=4)),
                ('mes', models.IntegerField(max_length=2)),
                ('sigla_uf', models.CharField(max_length=3)),
                ('tipo_consumo', models.CharField(max_length=20)),
                ('numero_consumidores', models.IntegerField(max_length=12)),
                ('consumo', models.FloatField(max_length=12)),
            ],
        ),
    ]
