# Generated by Django 5.0.6 on 2024-07-16 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_consumo_eletrica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos_tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=15)),
                ('preco', models.FloatField()),
                ('total_vendas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('avaliacao', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('data_venda', models.DateField()),
                ('tipo_produto', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=25)),
                ('garantia', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)])),
            ],
        ),
    ]
