# Generated by Django 5.0.6 on 2024-07-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_top_100_eletrica_2024_vendas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_100_eletrica_2024',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
